export const countries = [
  { label: "Afghanistan", value: "afghanistan", timezone: "Asia/Kabul" },
  { label: "Albania", value: "albania", timezone: "Europe/Tirane" },
  { label: "Algeria", value: "algeria", timezone: "Africa/Algiers" },
  { label: "Andorra", value: "andorra", timezone: "Europe/Andorra" },
  { label: "Angola", value: "angola", timezone: "Africa/Luanda" },
  {
    label: "Antigua and Barbuda",
    value: "antigua_and_barbuda",
    timezone: "America/Antigua",
  },
  {
    label: "Argentina",
    value: "argentina",
    timezone: "America/Argentina/Buenos_Aires",
  },
  { label: "Armenia", value: "armenia", timezone: "Asia/Yerevan" },
  { label: "Australia", value: "australia", timezone: "Australia/Sydney" },
  { label: "Austria", value: "austria", timezone: "Europe/Vienna" },
  { label: "Azerbaijan", value: "azerbaijan", timezone: "Asia/Baku" },
  { label: "Bahamas", value: "bahamas", timezone: "America/Nassau" },
  { label: "Bahrain", value: "bahrain", timezone: "Asia/Bahrain" },
  { label: "Bangladesh", value: "bangladesh", timezone: "Asia/Dhaka" },
  { label: "Barbados", value: "barbados", timezone: "America/Barbados" },
  { label: "Belarus", value: "belarus", timezone: "Europe/Minsk" },
  { label: "Belgium", value: "belgium", timezone: "Europe/Brussels" },
  { label: "Belize", value: "belize", timezone: "America/Belize" },
  { label: "Benin", value: "benin", timezone: "Africa/Porto-Novo" },
  { label: "Bhutan", value: "bhutan", timezone: "Asia/Thimphu" },
  { label: "Bolivia", value: "bolivia", timezone: "America/La_Paz" },
  {
    label: "Bosnia and Herzegovina",
    value: "bosnia_and_herzegovina",
    timezone: "Europe/Sarajevo",
  },
  { label: "Botswana", value: "botswana", timezone: "Africa/Gaborone" },
  { label: "Brazil", value: "brazil", timezone: "America/Sao_Paulo" },
  { label: "Brunei", value: "brunei", timezone: "Asia/Brunei" },
  { label: "Bulgaria", value: "bulgaria", timezone: "Europe/Sofia" },
  {
    label: "Burkina Faso",
    value: "burkina_faso",
    timezone: "Africa/Ouagadougou",
  },
  { label: "Burundi", value: "burundi", timezone: "Africa/Gitega" },
  { label: "Cabo Verde", value: "cabo_verde", timezone: "Atlantic/Cape_Verde" },
  { label: "Cambodia", value: "cambodia", timezone: "Asia/Phnom_Penh" },
  { label: "Cameroon", value: "cameroon", timezone: "Africa/Douala" },
  { label: "Canada", value: "canada", timezone: "America/Toronto" },
  {
    label: "Central African Republic",
    value: "central_african_republic",
    timezone: "Africa/Bangui",
  },
  { label: "Chad", value: "chad", timezone: "Africa/N'Djamena" },
  { label: "Chile", value: "chile", timezone: "America/Santiago" },
  { label: "China", value: "china", timezone: "Asia/Shanghai" },
  { label: "Colombia", value: "colombia", timezone: "America/Bogota" },
  { label: "Comoros", value: "comoros", timezone: "Africa/Moroni" },
  {
    label: "Congo, Democratic Republic of the",
    value: "congo_democratic_republic",
    timezone: "Africa/Kinshasa",
  },
  {
    label: "Congo, Republic of the",
    value: "congo_republic",
    timezone: "Africa/Brazzaville",
  },
  { label: "Costa Rica", value: "costa_rica", timezone: "America/Costa_Rica" },
  { label: "Croatia", value: "croatia", timezone: "Europe/Zagreb" },
  { label: "Cuba", value: "cuba", timezone: "America/Havana" },
  { label: "Cyprus", value: "cyprus", timezone: "Asia/Nicosia" },
  {
    label: "Czech Republic",
    value: "czech_republic",
    timezone: "Europe/Prague",
  },
  { label: "Denmark", value: "denmark", timezone: "Europe/Copenhagen" },
  { label: "Djibouti", value: "djibouti", timezone: "Africa/Djibouti" },
  { label: "Dominica", value: "dominica", timezone: "America/Dominica" },
  {
    label: "Dominican Republic",
    value: "dominican_republic",
    timezone: "America/Santo_Domingo",
  },
  { label: "Ecuador", value: "ecuador", timezone: "America/Guayaquil" },
  { label: "Egypt", value: "egypt", timezone: "Africa/Cairo" },
  {
    label: "El Salvador",
    value: "el_salvador",
    timezone: "America/El_Salvador",
  },
  {
    label: "Equatorial Guinea",
    value: "equatorial_guinea",
    timezone: "Africa/Malabo",
  },
  { label: "Eritrea", value: "eritrea", timezone: "Africa/Asmara" },
  { label: "Estonia", value: "estonia", timezone: "Europe/Tallinn" },
  { label: "Eswatini", value: "eswatini", timezone: "Africa/Mbabane" },
  { label: "Ethiopia", value: "ethiopia", timezone: "Africa/Addis_Ababa" },
  { label: "Fiji", value: "fiji", timezone: "Pacific/Fiji" },
  { label: "Finland", value: "finland", timezone: "Europe/Helsinki" },
  { label: "France", value: "france", timezone: "Europe/Paris" },
  { label: "Gabon", value: "gabon", timezone: "Africa/Libreville" },
  { label: "Gambia", value: "gambia", timezone: "Africa/Banjul" },
  { label: "Georgia", value: "georgia", timezone: "Asia/Tbilisi" },
  { label: "Germany", value: "germany", timezone: "Europe/Berlin" },
  { label: "Ghana", value: "ghana", timezone: "Africa/Accra" },
  { label: "Greece", value: "greece", timezone: "Europe/Athens" },
  { label: "Grenada", value: "grenada", timezone: "America/Grenada" },
  { label: "Guatemala", value: "guatemala", timezone: "America/Guatemala" },
  { label: "Guinea", value: "guinea", timezone: "Africa/Conakry" },
  { label: "Guinea-Bissau", value: "guinea_bissau", timezone: "Africa/Bissau" },
  { label: "Guyana", value: "guyana", timezone: "America/Guyana" },
  { label: "Haiti", value: "haiti", timezone: "America/Port-au-Prince" },
  { label: "Honduras", value: "honduras", timezone: "America/Tegucigalpa" },
  { label: "Hungary", value: "hungary", timezone: "Europe/Budapest" },
  { label: "Iceland", value: "iceland", timezone: "Atlantic/Reykjavik" },
  { label: "India", value: "india", timezone: "Asia/Kolkata" },
  { label: "Indonesia", value: "indonesia", timezone: "Asia/Jakarta" },
  { label: "Iran", value: "iran", timezone: "Asia/Tehran" },
  { label: "Iraq", value: "iraq", timezone: "Asia/Baghdad" },
  { label: "Ireland", value: "ireland", timezone: "Europe/Dublin" },
  { label: "Israel", value: "israel", timezone: "Asia/Jerusalem" },
  { label: "Italy", value: "italy", timezone: "Europe/Rome" },
  { label: "Jamaica", value: "jamaica", timezone: "America/Jamaica" },
  { label: "Japan", value: "japan", timezone: "Asia/Tokyo" },
  { label: "Jordan", value: "jordan", timezone: "Asia/Amman" },
  { label: "Kazakhstan", value: "kazakhstan", timezone: "Asia/Almaty" },
  { label: "Kenya", value: "kenya", timezone: "Africa/Nairobi" },
  { label: "Kiribati", value: "kiribati", timezone: "Pacific/Tarawa" },
  { label: "Korea, North", value: "korea_north", timezone: "Asia/Pyongyang" },
  { label: "Korea, South", value: "korea_south", timezone: "Asia/Seoul" },
  { label: "Kuwait", value: "kuwait", timezone: "Asia/Kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan", timezone: "Asia/Bishkek" },
  { label: "Laos", value: "laos", timezone: "Asia/Vientiane" },
  { label: "Latvia", value: "latvia", timezone: "Europe/Riga" },
  { label: "Lebanon", value: "lebanon", timezone: "Asia/Beirut" },
  { label: "Lesotho", value: "lesotho", timezone: "Africa/Maseru" },
  { label: "Liberia", value: "liberia", timezone: "Africa/Monrovia" },
  { label: "Libya", value: "libya", timezone: "Africa/Tripoli" },
  { label: "Liechtenstein", value: "liechtenstein", timezone: "Europe/Vaduz" },
  { label: "Lithuania", value: "lithuania", timezone: "Europe/Vilnius" },
  { label: "Luxembourg", value: "luxembourg", timezone: "Europe/Luxembourg" },
  { label: "Madagascar", value: "madagascar", timezone: "Indian/Antananarivo" },
  { label: "Malawi", value: "malawi", timezone: "Africa/Blantyre" },
  { label: "Malaysia", value: "malaysia", timezone: "Asia/Kuala_Lumpur" },
  { label: "Maldives", value: "maldives", timezone: "Asia/Male" },
  { label: "Mali", value: "mali", timezone: "Africa/Bamako" },
  { label: "Malta", value: "malta", timezone: "Europe/Valletta" },
  {
    label: "Marshall Islands",
    value: "marshall_islands",
    timezone: "Pacific/Majuro",
  },
  { label: "Mauritania", value: "mauritania", timezone: "Africa/Nouakchott" },
  { label: "Mauritius", value: "mauritius", timezone: "Indian/Mauritius" },
  { label: "Mexico", value: "mexico", timezone: "America/Mexico_City" },
  { label: "Micronesia", value: "micronesia", timezone: "Pacific/Chuuk" },
  { label: "Moldova", value: "moldova", timezone: "Europe/Chisinau" },
  { label: "Monaco", value: "monaco", timezone: "Europe/Monaco" },
  { label: "Mongolia", value: "mongolia", timezone: "Asia/Ulaanbaatar" },
  { label: "Montenegro", value: "montenegro", timezone: "Europe/Podgorica" },
  { label: "Morocco", value: "morocco", timezone: "Africa/Casablanca" },
  { label: "Mozambique", value: "mozambique", timezone: "Africa/Maputo" },
  { label: "Myanmar", value: "myanmar", timezone: "Asia/Yangon" },
  { label: "Namibia", value: "namibia", timezone: "Africa/Windhoek" },
  { label: "Nauru", value: "nauru", timezone: "Pacific/Nauru" },
  { label: "Nepal", value: "nepal", timezone: "Asia/Kathmandu" },
  { label: "Netherlands", value: "netherlands", timezone: "Europe/Amsterdam" },
  { label: "New Zealand", value: "new_zealand", timezone: "Pacific/Auckland" },
  { label: "Nicaragua", value: "nicaragua", timezone: "America/Managua" },
  { label: "Niger", value: "niger", timezone: "Africa/Niamey" },
  { label: "Nigeria", value: "nigeria", timezone: "Africa/Lagos" },
  {
    label: "North Macedonia",
    value: "north_macedonia",
    timezone: "Europe/Skopje",
  },
  { label: "Norway", value: "norway", timezone: "Europe/Oslo" },
  { label: "Oman", value: "oman", timezone: "Asia/Muscat" },
  { label: "Pakistan", value: "pakistan", timezone: "Asia/Karachi" },
  { label: "Palau", value: "palau", timezone: "Pacific/Palau" },
  { label: "Palestine", value: "palestine", timezone: "Asia/Gaza" },
  { label: "Panama", value: "panama", timezone: "America/Panama" },
  {
    label: "Papua New Guinea",
    value: "papua_new_guinea",
    timezone: "Pacific/Port_Moresby",
  },
  { label: "Paraguay", value: "paraguay", timezone: "America/Asuncion" },
  { label: "Peru", value: "peru", timezone: "America/Lima" },
  { label: "Philippines", value: "philippines", timezone: "Asia/Manila" },
  { label: "Poland", value: "poland", timezone: "Europe/Warsaw" },
  { label: "Portugal", value: "portugal", timezone: "Europe/Lisbon" },
  { label: "Qatar", value: "qatar", timezone: "Asia/Qatar" },
  { label: "Romania", value: "romania", timezone: "Europe/Bucharest" },
  { label: "Russia", value: "russia", timezone: "Europe/Moscow" },
  { label: "Rwanda", value: "rwanda", timezone: "Africa/Kigali" },
  {
    label: "Saint Kitts and Nevis",
    value: "saint_kitts_and_nevis",
    timezone: "America/St_Kitts",
  },
  { label: "Saint Lucia", value: "saint_lucia", timezone: "America/St_Lucia" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint_vincent_and_the_grenadines",
    timezone: "America/St_Vincent",
  },
  { label: "Samoa", value: "samoa", timezone: "Pacific/Apia" },
  { label: "San Marino", value: "san_marino", timezone: "Europe/San_Marino" },
  {
    label: "Sao Tome and Principe",
    value: "sao_tome_and_principe",
    timezone: "Africa/Sao_Tome",
  },
  { label: "Saudi Arabia", value: "saudi_arabia", timezone: "Asia/Riyadh" },
  { label: "Senegal", value: "senegal", timezone: "Africa/Dakar" },
  { label: "Serbia", value: "serbia", timezone: "Europe/Belgrade" },
  { label: "Seychelles", value: "seychelles", timezone: "Indian/Victoria" },
  { label: "Sierra Leone", value: "sierra_leone", timezone: "Africa/Freetown" },
  { label: "Singapore", value: "singapore", timezone: "Asia/Singapore" },
  { label: "Slovakia", value: "slovakia", timezone: "Europe/Bratislava" },
  { label: "Slovenia", value: "slovenia", timezone: "Europe/Ljubljana" },
  {
    label: "Solomon Islands",
    value: "solomon_islands",
    timezone: "Pacific/Guadalcanal",
  },
  { label: "Somalia", value: "somalia", timezone: "Africa/Mogadishu" },
  {
    label: "South Africa",
    value: "south_africa",
    timezone: "Africa/Johannesburg",
  },
  { label: "South Sudan", value: "south_sudan", timezone: "Africa/Juba" },
  { label: "Spain", value: "spain", timezone: "Europe/Madrid" },
  { label: "Sri Lanka", value: "sri_lanka", timezone: "Asia/Colombo" },
  { label: "Sudan", value: "sudan", timezone: "Africa/Khartoum" },
  { label: "Suriname", value: "suriname", timezone: "America/Paramaribo" },
  { label: "Sweden", value: "sweden", timezone: "Europe/Stockholm" },
  { label: "Switzerland", value: "switzerland", timezone: "Europe/Zurich" },
  { label: "Syria", value: "syria", timezone: "Asia/Damascus" },
  { label: "Taiwan", value: "taiwan", timezone: "Asia/Taipei" },
  { label: "Tajikistan", value: "tajikistan", timezone: "Asia/Dushanbe" },
  { label: "Tanzania", value: "tanzania", timezone: "Africa/Dar_es_Salaam" },
  { label: "Thailand", value: "thailand", timezone: "Asia/Bangkok" },
  { label: "Timor-Leste", value: "timor_leste", timezone: "Asia/Dili" },
  { label: "Togo", value: "togo", timezone: "Africa/Lome" },
  { label: "Tonga", value: "tonga", timezone: "Pacific/Tongatapu" },
  {
    label: "Trinidad and Tobago",
    value: "trinidad_and_tobago",
    timezone: "America/Port_of_Spain",
  },
  { label: "Tunisia", value: "tunisia", timezone: "Africa/Tunis" },
  { label: "Turkey", value: "turkey", timezone: "Europe/Istanbul" },
  { label: "Turkmenistan", value: "turkmenistan", timezone: "Asia/Ashgabat" },
  { label: "Tuvalu", value: "tuvalu", timezone: "Pacific/Funafuti" },
  { label: "Uganda", value: "uganda", timezone: "Africa/Kampala" },
  { label: "Ukraine", value: "ukraine", timezone: "Europe/Kiev" },
  {
    label: "United Arab Emirates",
    value: "united_arab_emirates",
    timezone: "Asia/Dubai",
  },
  {
    label: "United Kingdom",
    value: "united_kingdom",
    timezone: "Europe/London",
  },
  {
    label: "United States",
    value: "united_states",
    timezone: "America/New_York",
  },
  { label: "Uruguay", value: "uruguay", timezone: "America/Montevideo" },
  { label: "Uzbekistan", value: "uzbekistan", timezone: "Asia/Tashkent" },
  { label: "Vanuatu", value: "vanuatu", timezone: "Pacific/Efate" },
  { label: "Vatican City", value: "vatican_city", timezone: "Europe/Vatican" },
  { label: "Venezuela", value: "venezuela", timezone: "America/Caracas" },
  { label: "Vietnam", value: "vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { label: "Yemen", value: "yemen", timezone: "Asia/Aden" },
  { label: "Zambia", value: "zambia", timezone: "Africa/Lusaka" },
  { label: "Zimbabwe", value: "zimbabwe", timezone: "Africa/Harare" },
];
