const timezones = [
  { value: "Etc/GMT-12", label: "(GMT-12:00) International Date Line West" },
  { value: "Pacific/Midway", label: "(GMT-11:00) Midway Island, Samoa" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(GMT-09:00) Alaska" },
  {
    value: "America/Los_Angeles",
    label: "(GMT-08:00) Pacific Time (US & Canada)",
  },
  { value: "America/Tijuana", label: "(GMT-08:00) Tijuana, Baja California" },
  { value: "America/Denver", label: "(GMT-07:00) Mountain Time (US & Canada)" },
  { value: "America/Phoenix", label: "(GMT-07:00) Arizona" },
  { value: "America/Chicago", label: "(GMT-06:00) Central Time (US & Canada)" },
  { value: "America/Mexico_City", label: "(GMT-06:00) Mexico City" },
  {
    value: "America/New_York",
    label: "(GMT-05:00) Eastern Time (US & Canada)",
  },
  { value: "America/Bogota", label: "(GMT-05:00) Bogota, Lima, Quito" },
  { value: "America/Caracas", label: "(GMT-04:30) Caracas" },
  { value: "America/Halifax", label: "(GMT-04:00) Atlantic Time (Canada)" },
  { value: "America/Santiago", label: "(GMT-04:00) Santiago" },
  { value: "America/St_Johns", label: "(GMT-03:30) Newfoundland" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "(GMT-03:00) Buenos Aires",
  },
  { value: "America/Sao_Paulo", label: "(GMT-03:00) Brasilia" },
  { value: "Atlantic/Azores", label: "(GMT-01:00) Azores" },
  { value: "Europe/London", label: "(GMT+00:00) London, Dublin, Lisbon" },
  { value: "Europe/Paris", label: "(GMT+01:00) Paris, Madrid, Berlin, Rome" },
  { value: "Europe/Warsaw", label: "(GMT+01:00) Warsaw, Prague, Brussels" },
  {
    value: "Africa/Johannesburg",
    label: "(GMT+02:00) South Africa Standard Time",
  },
  {
    value: "Asia/Istanbul",
    label: "(GMT+03:00) Istanbul, Moscow, St. Petersburg",
  },
  { value: "Asia/Dubai", label: "(GMT+04:00) Dubai, Abu Dhabi, Muscat" },
  { value: "Asia/Kolkata", label: "(GMT+05:30) India Standard Time" },
  { value: "Asia/Kathmandu", label: "(GMT+05:45) Kathmandu" },
  { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
  {
    value: "Asia/Shanghai",
    label: "(GMT+08:00) China Standard Time - Shanghai",
  },
  { value: "Asia/Hong_Kong", label: "(GMT+08:00) Hong Kong Standard Time" },
  { value: "Asia/Manila", label: "(GMT+08:00) Philippine Standard Time" },
  { value: "Asia/Singapore", label: "(GMT+08:00) Singapore Standard Time" },
  { value: "Asia/Tokyo", label: "(GMT+09:00) Japan Standard Time" },
  { value: "Asia/Seoul", label: "(GMT+09:00) Korea Standard Time" },
  {
    value: "Australia/Sydney",
    label: "(GMT+10:00) Sydney, Melbourne, Canberra",
  },
  { value: "Pacific/Noumea", label: "(GMT+11:00) New Caledonia Standard Time" },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland, Wellington" },
  { value: "Pacific/Fiji", label: "(GMT+12:00) Fiji Standard Time" },
  { value: "Pacific/Apia", label: "(GMT+13:00) Samoa Standard Time" },
  { value: "Pacific/Tongatapu", label: "(GMT+13:00) Tonga Standard Time" },
  { value: "Pacific/Kiritimati", label: "(GMT+14:00) Line Islands Time" },
];

export default timezones;
