const timezones = [
  { label: "(GMT-12:00) International Date Line West", value: "Etc/GMT+12" },
  { label: "(GMT-11:00) Midway Island, Samoa", value: "Pacific/Midway" },
  { label: "(GMT-10:00) Hawaii", value: "Pacific/Honolulu" },
  { label: "(GMT-09:00) Alaska", value: "America/Anchorage" },
  {
    label: "(GMT-08:00) Pacific Time (US & Canada)",
    value: "America/Los_Angeles",
  },
  {
    label: "(GMT-08:00) China Standard Time - Shanghai",
    value: "Asia/Shanghai",
  },
  { label: "(GMT-08:00) Singapore Standard Time", value: "Asia/Singapore" },
  { label: "(GMT-08:00) Hong Kong Time", value: "Asia/Hong_Kong" },
  {
    label: "(GMT-08:00) Western Australia Standard Time",
    value: "Australia/Perth",
  },
  { label: "(GMT-08:00) Taiwan Time", value: "Asia/Taipei" },
  { label: "(GMT-08:00) Brunei Time", value: "Asia/Brunei" },
  { label: "(GMT-08:00) Ulaanbaatar Time", value: "Asia/Ulaanbaatar" },
  { label: "(GMT-08:00) Irkutsk Time", value: "Asia/Irkutsk" },
  { label: "(GMT-07:00) Mountain Time (US & Canada)", value: "America/Denver" },
  { label: "(GMT-07:00) Chihuahua, La Paz", value: "America/Chihuahua" },
  { label: "(GMT-07:00) Pacific Time (Mexico)", value: "America/Tijuana" },
  { label: "(GMT-06:00) Central Time (US & Canada)", value: "America/Chicago" },
  { label: "(GMT-06:00) Mexico City", value: "America/Mexico_City" },
  { label: "(GMT-06:00) Central America", value: "America/Guatemala" },
  {
    label: "(GMT-05:00) Eastern Time (US & Canada)",
    value: "America/New_York",
  },
  { label: "(GMT-05:00) Haiti", value: "America/Port-au-Prince" },
  { label: "(GMT-05:00) Cuba", value: "America/Havana" },
  { label: "(GMT-04:00) Atlantic Time (Canada)", value: "America/Halifax" },
  { label: "(GMT-04:00) Bolivia", value: "America/La_Paz" },
  { label: "(GMT-04:00) Venezuela", value: "America/Caracas" },
  {
    label: "(GMT-03:00) Argentina Time",
    value: "America/Argentina/Buenos_Aires",
  },
  { label: "(GMT-03:00) Brazil, Brasília", value: "America/Brasilia" },
  { label: "(GMT-03:00) Greenland", value: "America/Nuuk" },
  { label: "(GMT-02:00) Mid-Atlantic", value: "Atlantic/Azores" },
  { label: "(GMT-01:00) Azores", value: "Atlantic/Azores" },
  { label: "(GMT+00:00) Greenwich Mean Time", value: "Etc/GMT" },
  { label: "(GMT+00:00) Western European Time", value: "Europe/London" },
  { label: "(GMT+01:00) Central European Time", value: "Europe/Berlin" },
  { label: "(GMT+01:00) West Africa Time", value: "Africa/Lagos" },
  {
    label: "(GMT+01:00) Central European Summer Time",
    value: "Europe/Budapest",
  },
  { label: "(GMT+02:00) Eastern European Time", value: "Europe/Helsinki" },
  { label: "(GMT+02:00) Central Africa Time", value: "Africa/Harare" },
  { label: "(GMT+02:00) Israel Standard Time", value: "Asia/Jerusalem" },
  { label: "(GMT+03:00) Moscow, St. Petersburg", value: "Europe/Moscow" },
  { label: "(GMT+03:00) East Africa Time", value: "Africa/Nairobi" },
  { label: "(GMT+03:30) Iran Standard Time", value: "Asia/Tehran" },
  { label: "(GMT+04:00) Arabian Standard Time", value: "Asia/Riyadh" },
  { label: "(GMT+04:00) Azerbaijan Standard Time", value: "Asia/Baku" },
  { label: "(GMT+04:00) Samara Time", value: "Europe/Samara" },
  { label: "(GMT+05:00) Pakistan Standard Time", value: "Asia/Karachi" },
  { label: "(GMT+05:00) Uzbekistan Standard Time", value: "Asia/Tashkent" },
  { label: "(GMT+05:30) India Standard Time", value: "Asia/Kolkata" },
  { label: "(GMT+05:45) Nepal Time", value: "Asia/Katmandu" },
  { label: "(GMT+06:00) Bangladesh Standard Time", value: "Asia/Dhaka" },
  { label: "(GMT+06:00) Bhutan Time", value: "Asia/Thimphu" },
  { label: "(GMT+06:30) Cocos Islands Time", value: "Australia/Cocos" },
  { label: "(GMT+07:00) Indochina Time", value: "Asia/Bangkok" },
  { label: "(GMT+07:00) Vietnam Time", value: "Asia/Ho_Chi_Minh" },
  {
    label: "(GMT+08:00) China Standard Time - Shanghai",
    value: "Asia/Shanghai",
  },
  { label: "(GMT+08:00) Singapore Standard Time", value: "Asia/Singapore" },
  { label: "(GMT+08:00) Hong Kong Time", value: "Asia/Hong_Kong" },
  { label: "(GMT+08:00) Malaysia Standard Time", value: "Asia/Kuala_Lumpur" },
  {
    label: "(GMT+08:00) Western Australia Standard Time",
    value: "Australia/Perth",
  },
  { label: "(GMT+08:00) Taiwan Time", value: "Asia/Taipei" },
  { label: "(GMT+08:00) Brunei Time", value: "Asia/Brunei" },
  { label: "(GMT+08:00) Ulaanbaatar Time", value: "Asia/Ulaanbaatar" },
  { label: "(GMT+08:00) Irkutsk Time", value: "Asia/Irkutsk" },
  { label: "(GMT+09:00) Japan Standard Time", value: "Asia/Tokyo" },
  { label: "(GMT+09:00) Korea Standard Time", value: "Asia/Seoul" },
  {
    label: "(GMT+09:30) Australian Central Standard Time",
    value: "Australia/Adelaide",
  },
  {
    label: "(GMT+10:00) Australian Eastern Standard Time",
    value: "Australia/Sydney",
  },
  { label: "(GMT+10:00) Vladivostok Time", value: "Asia/Vladivostok" },
  {
    label: "(GMT+11:00) Solomon Islands, Magadan",
    value: "Pacific/Guadalcanal",
  },
  { label: "(GMT+12:00) Fiji, Kamchatka", value: "Pacific/Fiji" },
  { label: "(GMT+12:00) Auckland, Wellington", value: "Pacific/Auckland" },
];
